version: '3.7'

volumes:
  mongodb_data:
    driver: local

networks:
  mongodb_network:
    driver: bridge

services:
  mongodb:
    container_name: db
    restart: always
    networks:
      - mongodb_network
    image: mongo:7.0.8-jammy
    env_file:
      - ./docker-cmopose.env
    volumes:
      - mongodb_data:/data/db

  bot:
    container_name: bot
    networks:
      - mongodb_network
    restart: always
    build:
      context: bot/
      dockerfile: bot.dockerfile
    env_file:
      - ./docker-compose.env
    depends_on:
      - mongodb
